# Generated by Django 5.0.2 on 2024-02-26 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerVehicles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('experience_points', models.IntegerField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.players')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.tanks')),
            ],
        ),
    ]
