# Generated by Django 5.0.2 on 2024-02-26 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('achievement_name', models.CharField(max_length=100)),
                ('achievement_description', models.TextField()),
                ('date_achieved', models.DateField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.players')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRanking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ranking_points', models.IntegerField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.players')),
            ],
        ),
    ]
