# Generated by Django 5.0.2 on 2024-02-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tank_name', models.CharField(max_length=100)),
                ('tank_type', models.CharField(choices=[('light', 'Легкий'), ('medium', 'Средний'), ('heavy', 'Тяжелый')], max_length=10)),
                ('tank_description', models.TextField()),
                ('damage_points', models.IntegerField()),
                ('armor_points', models.IntegerField()),
                ('speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
